/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2024-03-23 08:58:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class User_0020Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function check(){\r\n");
      out.write("	var name=document.getElementById(\"name\");\r\n");
      out.write("	 var email=document.getElementById(\"email\");\r\n");
      out.write("	 var mobileNumber=document.getElementById(\"phoneNumber\");\r\n");
      out.write("	 var userdob=document.getElementById(\"dateOfBirth\"); \r\n");
      out.write("	 var location=document.getElementById(\"location\"); \r\n");
      out.write("	 var file=document.getElementById(\"document\");\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("		\r\n");
      out.write("	 var nameregx=/^[a-zA-Z ]+$/\r\n");
      out.write("	 var emailregx=/^[a-zA-Z][a-zA-Z0-9]*@[a-zA-Z0-9]+[.]com$/\r\n");
      out.write("	 var mobileNumbeeRegx=/^[6-9][0-9]{9}$/\r\n");
      out.write("	\r\n");
      out.write("		 const d = new Date();\r\n");
      out.write("		let year = d.getFullYear();\r\n");
      out.write("		var n=userdob.value.split(\"-\");\r\n");
      out.write("		var age=year-n[0];\r\n");
      out.write("		 \r\n");
      out.write("	 \r\n");
      out.write("	 if(name.value.length==0 || !nameregx.test(name.value)){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**invalid name\";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 \r\n");
      out.write("	 else if(mobileNumber.value.length==0 || !mobileNumbeeRegx.test(mobileNumber.value) ){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**invalid mobile number\";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 else if( email.value.length==0 || !emailregx.test(email.value)){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**invalid email\";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 else if( userdob.value.length==0 ){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**invalid Date of Birth \";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 else if( age<18){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**Age should be not less than 21 \";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 else if(location.value.length==0){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**please select location\";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 else if(file.value.length==0){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**please upload document\";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 else if(file.files[0].size > 2500000){\r\n");
      out.write("			document.getElementById(\"result\").innerHTML= \"**file size not more than 2MB\";\r\n");
      out.write("			return false;	\r\n");
      out.write("		 }\r\n");
      out.write("	 \r\n");
      out.write("	\r\n");
      out.write("	 return true;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("		body{\r\n");
      out.write("		    background: url(\"https://image.freepik.com/free-photo/top-view-business-office-desk-background-the-applying-for-a-job-form-and-pen-pencil-eyeglasses-tree-on-wooden-table-background-with-copy-space_1921-21.jpg\") no-repeat;\r\n");
      out.write("		    background-position: center;\r\n");
      out.write("		    background-size: cover;\r\n");
      out.write("		    min-height: 100vh;\r\n");
      out.write("		    width: 100%;\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		.container{\r\n");
      out.write("		    display: flex;\r\n");
      out.write("		    justify-content: center;\r\n");
      out.write("		    align-items: center;\r\n");
      out.write("		    min-height: 100vh;\r\n");
      out.write("		}\r\n");
      out.write("		.form-box{	\r\n");
      out.write("		    position: relative;\r\n");
      out.write("		    width: 600px;\r\n");
      out.write("		    height: 600px;\r\n");
      out.write("		    border: 2px solid rgba(255, 255, 2550.5);\r\n");
      out.write("		    border-radius: 20px;\r\n");
      out.write("		    backdrop-filter: blur(2px);\r\n");
      out.write("		    display: flex;\r\n");
      out.write("		    justify-content: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.form-box h2{\r\n");
      out.write("		    color:black;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    font-size: 32px;\r\n");
      out.write("		    \r\n");
      out.write("		}\r\n");
      out.write("		.form-box .input-box{\r\n");
      out.write("		    position: relative;\r\n");
      out.write("		    margin: 30px 0;\r\n");
      out.write("		    font-size: 17px;\r\n");
      out.write("		}\r\n");
      out.write("		.button{\r\n");
      out.write("		    color: red;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    \r\n");
      out.write("		   \r\n");
      out.write("		}\r\n");
      out.write("		#result{\r\n");
      out.write("		    color: red;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write(" </style>\r\n");
      out.write("		 \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("        <div class=\"form-box\">\r\n");
      out.write("            <form action=\"user_register\" name=\"Formfill\"  method=\"post\"  >\r\n");
      out.write("                <h2><u>Registration Form</u> </h2>\r\n");
      out.write("                <p  id=\"result\"></p>\r\n");
      out.write("                <div class=\"input-box\">Enter Name:\r\n");
      out.write("                    <input  placeholder=\"abc\"   name=\"name\" id=\"name\" >\r\n");
      out.write("                    <span id=\"result\"></span>   \r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-box\">Enter Email:\r\n");
      out.write("                    <input type=\"email\" placeholder=\"abc@gmail.com\" name=\"email\" id=\"email\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"input-box\">Date Of Birth:\r\n");
      out.write("                    <input type=\"date\" name=\"dateOfBirth\" id=\"dateOfBirth\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-box\">Mobile Number:\r\n");
      out.write("                    <input type=\"tel\" placeholder=\"987*****\" name=\"phoneNumber\" id=\"phoneNumber\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-box\">Select Location\r\n");
      out.write("                    <select name=\"location\" id=\"location\"  >\r\n");
      out.write("                    <option> </option>\r\n");
      out.write("						<option> Any Location</option>\r\n");
      out.write("						<option> Bangalore </option>\r\n");
      out.write("						<option> Hyderabad </option>\r\n");
      out.write("						<option> Chennai </option>\r\n");
      out.write("						<option> New Delhi</option>\r\n");
      out.write("				</select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">Identification document:\r\n");
      out.write("                    <input type=\"file\" name=\"document\" id=\"document\" accept=\".png, .jpg, .jpeg, .pdf\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"button\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Register\" onclick=\"return  check()\">\r\n");
      out.write("                        <a href=\"getelenmentbyid.jsp\">Get Element By Id</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("               <h6> <u> *mandatory</u> \r\n");
      out.write("                <ul>\r\n");
      out.write("               <li>All fields are mandatory.</li>\r\n");
      out.write("               <li>Name  must have contains only alphabets[A-z/a-z].</li>\r\n");
      out.write("               <li>Duplicate values are not allowed for email field and mobile Number.</li>\r\n");
      out.write("               <li>Age should be above 21 years age as on date.</li>\r\n");
      out.write("               <li>Identification document must be size in less than or equal 2MB and<br> must be in format of PDF or PNG format. </li>\r\n");
      out.write("               </ul></h6> \r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
